### ISSUE TITLE
 Issue in accessing web server through browser 

### ISSUE THREAD

**Issue by odidev** [jasonrandrews/arm-software-developers#7]
Hi Team, 

As per your suggestion in previous [issue](https://github.com/jasonrandrews/arm-software-developers/issues/6), I am able to successfully run hugo server command but not able to access the web server through web server, please have a look at the logs:

```
ubuntu@ip-172-31-12-172:~/sakshi/arm-software-developers$ hugo server
hugo: downloading modules …
hugo: collected modules in 13678 ms
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

                   | EN
-------------------+------
  Pages            | 267
  Paginator pages  |   0
  Non-page files   |  13
  Static files     |  51
  Processed images |   8
  Aliases          |   3
  Sitemaps         |   1
  Cleaned          |   0

Built in 2674 ms
Watching for changes in /home/ubuntu/sakshi/arm-software-developers/{assets,content,layouts,package.json,static,themes}
Watching for config changes in /home/ubuntu/sakshi/arm-software-developers/config.toml, /home/ubuntu/sakshi/arm-software-developers/themes/docsy/config.toml, /home/ubuntu/sakshi/arm-software-developers/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

It would be really helpful if you could suggest how to run the web server in the browser.

**Comment by pareenaverma** [comment]
@odidev - Hugo server in only listening in localhost. That means that you can only access from your own machine.
By default Hugo server will create a server running on localhost port 1313. 

If your IP address is 192.168.1.20, providing the following flags to Hugo will will bind the server to your device’s IP address on your local network instead of localhost. Substitute your own IP address in place of my example address.

$ hugo server --bind 192.168.1.20 --baseURL http://192.168.1.20/

After doing this, any device on your local network can access the Hugo development server by visiting http://192.168.1.20:1313.

Alternatively you can also ssh with -L 1313:localhost:1313 and then localhost:1313 in the browser.
